apiVersion: v1
kind: Service
metadata:
  name: sse-server
  namespace: user-api
  labels:
    app: sse-server
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
      name: sse-server
  selector:
    app: sse-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sse-server
  namespace: user-api
  labels:
    app: sse-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sse-server
  template:
    metadata:
      labels:
        app: sse-server
        distribution: ccm
    spec:
      containers:
        - name: sse-server
          image: "us-east1-docker.pkg.dev/gothic-parser-227615/ccm/sse-server@sha256:d768fbe0ffedc6c09a53cc37f9445b7bd268915408a321624f913435e8d15ac7"
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "1"
              memory: "100Mi"
